import { Action } from '../action/Action';
import { ApiRequest, ApiRequestJSON } from '../api/ApiRequest';
import { QuerySource } from './BaseFilterSource';
import { RequestFilters, UsedFilters } from './RequestFilters';
export declare type FilterValueType = boolean | string | number | [string, FilterValueType] | null;
export declare type FilterJSON = {
    type: string;
    default: FilterValueType;
    options: [];
    options_request: ApiRequestJSON;
    null_is_option: boolean;
};
export declare type FilterParams = object;
declare type RequestFactory = (() => ApiRequest) | null;
export declare class Filter {
    type: string;
    name: string;
    private _action;
    private _defaultValue;
    private _nullIsOption;
    private _value;
    private _options;
    private _requestFactory;
    private _request;
    private _requestFilters;
    constructor(requestFilters?: RequestFilters);
    getAction(): Action;
    get value(): FilterValueType;
    set value(value: FilterValueType);
    get defaultValue(): FilterValueType;
    hasOptions(): boolean;
    hasOption(value: unknown): boolean;
    get options(): unknown[];
    get nullIsOption(): boolean;
    hasRequest(): boolean;
    get request(): ApiRequest | null;
    createActionFilter(action: Action, name: string, json: FilterJSON): Filter;
    createRequestFilter(requestFilters: RequestFilters): Filter;
    initFromUsed(usedFilters: UsedFilters): void;
    initFromQuerySource(query: QuerySource): void;
    toQuerySource(): QuerySource;
    hasDefaultValueSet(): boolean;
    reset(): boolean;
    serialize(): UsedFilters;
    protected valueToQuery(_value: unknown): string | undefined;
    protected queryToValue(_value: string): unknown | undefined;
    protected serializeValue(value: unknown): unknown | undefined;
    protected init(action: Action, name: string, defaultValue: FilterValueType, options: unknown[], nullIsOption: boolean, _requestFactory: RequestFactory): void;
}
export {};
//# sourceMappingURL=Filter.d.ts.map